spring.application.name=CollegeManagementSystem
#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/college_management?sslmode=disable
spring.datasource.username=springuser
spring.datasource.password=Luffy@123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

#logger config
logging.level.com.example.rakshit.CollegeManagementSystem.clients=trace
logging.level.com.example.rakshit.CollegeManagementSystem.config=INFO
logging.pattern.console=%d{dd-mm-yyyy hh:MM:ss} [%level] %c{1.} --- %m%n
logging.file.name=application.log
logging.config=classpath:logback-spring.xml

#actuator config
management.endpoints.web.exposure.include=*

#acutator info
management.info.env.enabled=true
info.app.author=Rakshit Shetty
info.app.version=1.0.0
info.app.documentation=https://shetty.com/docs
management.endpoint.env.show-values=always
management.info.build.enabled=true
management.info.git.enabled=true
management.info.java.enabled=true
management.info.os.enabled=true


#open api doc configuration. check swagger url
springdoc.api-docs.enabled = true

deploy.env = false

spring.devtools.restart.enabled = true

jwt.secretKey = ads9f6askj3h4k1hf86asdfiahkjh34a789s6df89ayshkjh3jkh786adsf78ay

# OAuth2 Configuration placeholders (Required for app to start with oauth2Login enabled)
spring.security.oauth2.client.registration.google.client-id=placeholder-client-id
spring.security.oauth2.client.registration.google.client-secret=placeholder-client-secret
