spring.application.name=CollegeManagementSystem
#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/college_management?sslmode=disable
spring.datasource.username=springuser
spring.datasource.password=Luffy@123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql


